version: "2"

services:
  bot:
    image: matsubara0507/adventar-line-bot
    command: wait.sh adventar-line-bot "${HTML_URL}" "/config/entry.json" "${DATASTORE_KIND}"
    volumes:
      - ./config:/config
    depends_on:
      - selenium
    networks:
      - apps
    environment:
      LANG: C.utf-8
      WD_HOST: selenium
      WD_PORT: 4444
      LINE_TOKEN:
      PROJECT_ID:
      TIME:
  selenium:
    image: selenium/standalone-chrome
    networks:
      - apps
    ports: ["4444"]

networks:
  apps:
